id: I9BE97124
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T01:42:07+00:00'
last_modified: '2022-06-08T03:28:47.969191+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG861
  title: བོད་ལྗོངས་ཀྱི་གཏམ་རྒྱུད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    AE31:
      image_group_id: I1KG900
      title: ''
      total_pages: 220
      order: 1
      base_file: AE31.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
