id: P005493
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG861
  title: བོད་ལྗོངས་ཀྱི་གཏམ་རྒྱུད
  author: ''
  volumes:
    3a155242496c41708bb3a87196a64960:
      image_group_id: I1KG900
      title: ''
      volume_number: 1
      total_pages: 220
      base_file: v001.txt
