id: P005493
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:54:01.922530
source_metadata:
  id: bdr:W1KG861
  title: བོད་ལྗོངས་ཀྱི་གཏམ་རྒྱུད
  author: ''
  volumes:
    3a155242496c41708bb3a87196a64960:
      image_group_id: I1KG900
      title: ''
      volume_number: 1
      total_pages: 220
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
